export enum ShoppingListActionNames {
  None,
  ADD_INGREDIENT = 'ADD_INGREDIENT',
  ADD_INGREDIENTS = 'ADD_INGREDIENTS',
  UPDATE_INGREDIENT = 'UPDATE_INGREDIENT',
  DELETE_INGREDIENT = 'DELETE_INGREDIENT',
  START_EDIT = 'START_EDIT',
  STOP_EDIT = 'STOP_EDIT'
}
